"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
__export(require("./constants"));
__export(require("./public/makeawait"));
__export(require("./public/makepromise"));
__export(require("./public/chunk"));
__export(require("./public/compact"));
__export(require("./public/flatten"));
__export(require("./public/ls"));
__export(require("./public/enumkeys"));
__export(require("./public/randominteger"));
__export(require("./public/round"));
__export(require("./public/roundup"));
__export(require("./public/rounddown"));
__export(require("./public/isthesame"));
__export(require("./public/thetypeof"));
__export(require("./public/toobject"));
__export(require("./public/objectify"));
__export(require("./public/stringify"));
__export(require("./public/clone"));
__export(require("./public/camelCase"));
__export(require("./public/capitalise"));
__export(require("./public/centeralign"));
__export(require("./public/hyphenate"));
__export(require("./public/leftalign"));
__export(require("./public/pad"));
__export(require("./public/padleft"));
__export(require("./public/padright"));
__export(require("./public/prints"));
__export(require("./public/randomtext"));
__export(require("./public/rightalign"));
__export(require("./public/tofixwidth"));
__export(require("./public/toparagraph"));
__export(require("./public/trim"));
__export(require("./public/trimleft"));
__export(require("./public/trimright"));
__export(require("./public/truncate"));
__export(require("./public/timer"));
__export(require("./public/stopwatch"));
//# sourceMappingURL=alpha.js.map